### ISSUE TITLE
some job title are missing for indeed.

### ISSUE THREAD

**Issue by bishaladhikari** [bishaladhikari/job-scraper-backend#17]
### Task description
The job title is missing, maybe we need to pick html of the span instead of title attribute.
<span title="web developer">Web developer</span>
<span title="">Frontend developer</span>

![image](https://user-images.githubusercontent.com/34532137/124646078-ece6e800-deb3-11eb-920a-e3699cc754ce.png)

What to do
- [x] pick correct attribute for job title that's not blank

**Comment by leezene** [comment]
I will verify from my side and work on it.

**Comment by leezene** [comment]
@bishaladhikari @rameshmarasini  @inirajbhandari @Suu-Zan 

### PR
-https://github.com/bishaladhikari/job-scraper-backend/pull/19#issue-684947070

### Work description
- fixed indeed scrapping company name, location, job title, and summary

### Affected areas
- indeed_job_scraper.py

### Supplements
checkout to branch fix_17_prabin and try testing the feature

**Comment by bishaladhikari** [comment]
@leezene 
Review done
