### ISSUE TITLE
Jobs within 30 days that have been posted

### ISSUE THREAD

**Issue by bishaladhikari** [bishaladhikari/job-scraper-backend#30]
### Task description

Only jobs that are posted within 30 days 
"date_posted" filters on API requests. The frontend app will have a dropdown saying and "All Time"(value=null) "Last 30 Days"(value=30).

**Comment by bishaladhikari** [comment]
@Suu-Zan 
Please attend to this. The milestone for this is near.

**Comment by inirajbhandari** [comment]
@bishaladhikari 
### PR
- #33 


### Work description
- [ ]  added logic to filter results within the date provided

### Supplements
Please checkout branch feature_30_niraj and test

**Comment by bishaladhikari** [comment]
@inirajbhandari 
Review
- does you PR also work for indeed and linkedin?
### Action To Do
- [  ] date_posted rules for linkedin
- [  ] date_posted rules for indeed
