### ISSUE TITLE
[60] Add Installation steps on readme

### ISSUE THREAD

**Issue by bishaladhikari** [bishaladhikari/job-scraper-backend#7]
### Task description
Add installation steps on readme
### what to do
Add installation and running commands in read me 

Estimate
 - [  ] research and estimate p:30
 - [  ] add commands on readme p:30

**Comment by bishaladhikari** [comment]
@Suu-Zan @leezene @inirajbhandari 
### PR Link
 - https://github.com/bishaladhikari/job-scraper-backend/pull/8
###  What I did
- added installation steps on readme
### Affected areas
Readme.md
### Supplement
n/a

**Comment by inirajbhandari** [comment]
Looks good to me 
@bishaladhikari

**Comment by leezene** [comment]
@bishaladhikari 
Review Done
